language: python
python:
  - "2.6"
  - "2.7"
  # PyPy versions
  - "pypy"
# command to install dependencies
services: # => 3
  - mysql
  - sqlite
install:
  - pip install Django
  - pip install djangorestframework
  - pip install six
  - pip install mysqlclient
  - pip install django-mysql
  - pip install python-google-places
  - pip install googlemaps
# command to run tests
before_script: cd bpDjango/
script:
  - python manage.py test
  