FORMAT: 1A
HOST: http://mathtap.de:1194/

# BestPlaces

The BestPlaces-API will be used to communicate between our server and the client

# Group User-Management

Everything which has to do with User-Management

# User-Actions [/user/{username}]

This will handle User-Management and all relating stuff.

+ Parameters

    + username: kolbma (string) - Username of the queried user

## Get User-object [GET]

This will return a user-object (JSON), which contains all informations from the database about the user.
Moreover it can be used to query if the username is already existing by doing GET with a already used username.

+ Response 200 (application/json)

    + Attributes (user)

+ Response 404 (application/json)

        {
            "detail": "Not found."
        }

## Update User-object [PUT]

This will get a User-Object as descriped above and will write it back to the database.

+ Request (application/json)

        {
            "email":"kolbma@live.de",
            "first_name":"Marco",
            "last_name":"Kolb",
            "hometown":"Hambrücken"
        }

+ Response 200 (application/json)

    + Attributes (user)
    
## Login [POST /api-token-auth]

To login a user, you'll have to login with username and password in order to get the Token for further requests.

+ Request (application/json)

        {
            "username":"kolbma",
            "password":"Test"
        }
        
+ Response 200 (application/json)

        {
            "token" : "80f8d09d703f70f7a30c5ecba4428f6376c16d6d"
        }

# Register [/user]

## Register User [POST]

This will register a user to the system and he will be written in the database.
Additionally to the attributes described for user, you have to provide a password.
(for testing purposes this will be plain text)

+ Request (application/json)

        {
            "username":"kolbma",
            "email":"kolbma@gmail.com",
            "password":"1234",
            "first_name":"Marco",
            "last-name":"Kolb",
            "hometown":"Hambrücken"
        }
   
+ Response 200 (application/json)

    + Headers
    
            Location: /user/kolbma
    
    + Body
    
            {
                "username":"kolbma",
                "email":"kolbma@gmail.com",
                "first_name":"Marco",
                "last_name":"Kolb",
                "hometown":"Hambrücken"
            }

# Group Places

Our application is called BestPlaces, so let's dive into the actual places-API

# Place [/place]

BestPlaces will user Google Places API to search and get information about the places.
A blank Place-Object will have those attributes:

## Search [GET /place/search{?q,location,long,lat,rad}]

Performs a search by the given parameters on google search api.

+ Parameters

    + q (string) - Query-string for google search api
    + long (number) - longitude where place should be searched
    + lat (number) - latitude where place should be searched
    + rad (number) - radius around geolocation, where the place should be searched
    + location (string) - location where to search

+ Response 200 (application/json)

    + Attributes (searchResult)
    
## Next Page [GET /place/search{?q,pt}]

Gets the next 20 results of the search before

+ Parameters
    + q (string) - Query-string for google search api
    + pt (string) - Only pagetoken should be passed to get next results
    
+ Response 200 (application/json)

    + Attributes (searchResult)

## Place Management [/place/{placeId}{?userId}]

+ Parameters

    + placeId (required, string) - Id of the place
    + userId (optional, string) - username, if you want to get user-specific place information

### Get place information [GET]

This returns all information about a place, identified by id, provided by 

+ Response 200 (application/json)

    + Attributes (fullPlace)

### Update place information [PUT]

Updating the additional information.

+ Request (application/json)

    + Attributes (fullPlace)

+ Response 200 (application/json)

    + Attributes (fullPlace)

## Visit [/visit{#visitId}]

A visit is a user-place-date-relationship, when you visit a place.

+ Fragments

    + visitId (required, string) - Id of the visit

### Get Visists [GET /visit{?username}]

Gets all visits of a defined User.

+ Parameters

    + username (string, required)

+ Response 200 (application/json)
    
    + Attributes (array[visit])

## Get one Visit [GET]

Gets one specific visit

+ Response 200 (application/json)

    + Attributes (visit)

## Update visit [PUT]

Updating the additional information.

+ Request (application/json)

    + Attributes (visit)

+ Response 200 (application/json)

    + Attributes (visit)
    
## Create Visit [POST /visit]

Creates a visit

+ Request (application/json)

    + Attributes (visit)
    
+ Response 200 (application/json)

    + Headers
    
            location: /user/{visitId}
        
    + Attributes (visit)
    
    

# Data Structures

## user (object)

+ username: kolbma (string) - Username of the user
+ email: kolbma@mathtap.de (string) - email of the user
+ first_name: Marco (string) - first name of the user
+ last_name: Kolb (string) - last name of the user
+ hometown: Hambrücken (string) - hometown of the use

## place (object)
+ placeId: ChIJd_6tlTcGl0cRVpRkbna3w68 (string) - id of the place (provided by Google)
+ name: Pizza Blitz Karlsruhe (string, required) - Name
+ geo (object, required) - Geometry of the place
    + longitude: 8.412367999999999 (number) - longitude of the place
    + latitude: 49.0090918 (number) - latitude of the place
+ formatted_address: Fritz-Erler-Straße 1, 76133 Karlsruhe, Germany (string) - Formatted adress of the place
+ openNow: true (boolean) - Says if place has opened now
+ rating: 5 (number, optional) - the average rating for the place (0-5)
+ photos (array[string])
+ categories: restaurant, food, poi (array[string])

## searchResult (object)
+ pagetoken: CvQB6QAAAOarkJZv809KOHr5GnsJ5HZ0Fe2aY (string, optional) - Token to get next results
+ results (array[place], required) - Results of the search

## fullPlace (place)
+ address (object, required) - Contains all informations on the address
    + street: Kaiserstraße (string) - Street of the place
    + streetNumber: 49 (number) - House number
    + town: Karlsruhe (string) - Town
    + zipCode: 76131 (number) - ZIP Code
+ phone_number: +49 721 376777 (string, optional) - Phone number (if provided)
+ website: http://www.pizzablitz.info/ (string, optional) - website (if provided)
+ openingHours (array[openingHours], optional)
+ favorite: false (boolean, optional) - determines if user marked place as favorite

## visit (object)
+ visitid: 1 (number, required) - Visit id
+ place: ChIJd_6tlTcGl0cRVpRkbna3w68 (string, required) - Place Id
+ user (string, required) - required user
+ visittime: 1480446791167 (number, required) - The time of the visit (in millis)
+ money: 10 (number, optional) - amount of money spent
+ duration: 12948 (number, optional) - duration of the visit in milliseconds
+ notes (string, optional) - notes for the visit

## openingHours (object)

+ day: 0 (number, required) - Day, (from 0 to 6)
+ opens (time, required) - Time written as number (0000-2399)
+ closes (time, optional) - Time written as number. (optional for 24h open)

## time (object)

+ hour: 11 (number, required) - Amount of hours
+ minute: 00 (number, required) - Amount of minutes

## review (object)

+ stars: 5 (number, required) - number 0-4, which rates the place
+ showName: true (boolean, required) - indicates whether user wants to present his name on the review
+ text: schöner ort (string, optional) - text for the review