FORMAT: 1A
HOST: http://mathtap.de:8888/

# BestPlaces

The BestPlaces-API will be used to communicate between our server and the client

# Group User-Management

Everything which has to do with User-Management

# User [/user/{username}]

This will handle User-Management and all relating stuff.

A user has the following standard attributes
- username
- email
- first_name
- last_name
- hometown

+ Parameters
  + username: 1 (required, string) - username

## Get User-object [GET]

This will return a user-object (JSON), which contains all informations from the database about the user

+ Response 200 (application/json)

        {
            "username":"kolbmarco",
            "email":"kolbma@gmail.com",
            "first_name":"Marco",
            "last_name":"Kolb",
            "hometown":"Hambrücken"
        }

## Update User-object [PUT]

This will get a User-Object as descriped above and will write it back to the database.

+ Request (application/json)

        {
            "email":"kolb.marco@live.de",
            "first_name":"Marco",
            "last_name":"Kolb",
            "hometown":"Hambrücken"
        }

+ Response 200 (application/json)

        {
          "email":"kolbma@live.de",
          "first_name":"Marco",
          "last_name":"Kolb",
          "hometown":"Hambrücken"
        }

## Register [/user]

### Register User [POST]

This will register a user to the system and he will be written in the database.
Additionally to the attributes described for user, you have to provide a password.
(for testing purposes this will be plain text)

+ Request (application/json)

        {
            "username":"kolbma",
            "email":"kolbma@gmail.com",
            "password":"1234",
            "first_name":"Marco",
            "last-name":"Kolb",
            "hometown":"Hambrücken"
        }
   
+ Response 200 (application/json)

    + Headers
    
            Location: /user/kolbma
    
    + Body
    
            {
                "username":"kolbma",
                "email":"kolbma@gmail.com",
                "first_name":"Marco",
                "last_name":"Kolb",
                "hometown":"Hambrücken"
            }