# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-01 17:38
from __future__ import unicode_literals

import BestPlaces.dbModels
import BestPlaces.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('placeid', models.CharField(db_column='placeId', max_length=28, primary_key=True, serialize=False)),
                ('additional_information', django_mysql.models.JSONField(blank=True, db_column='additionalInformation', default=dict, null=True)),
            ],
            options={
                'db_table': 'Place',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('visitid', models.AutoField(db_column='visitId', primary_key=True, serialize=False)),
                ('visitime', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('money', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('place', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='BestPlaces.Place')),
            ],
            options={
                'db_table': 'Visit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=45, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('hometown', models.CharField(blank=True, max_length=45, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Userplaceinformation',
            fields=[
                ('user', models.ForeignKey(default=BestPlaces.models.User, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('favorite', models.IntegerField(blank=True, null=True)),
                ('reviewtext', models.TextField(blank=True, db_column='reviewText', null=True)),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('reviewshowname', models.IntegerField(blank=True, db_column='reviewShowName', null=True)),
                ('place', models.ForeignKey(default=BestPlaces.dbModels.Place, on_delete=django.db.models.deletion.CASCADE, to='BestPlaces.Place')),
            ],
            options={
                'db_table': 'UserPlaceInformation',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='visit',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userplaceinformation',
            unique_together=set([('user', 'place')]),
        ),
    ]
