# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-15 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestPlaces', '0002_auto_20170501_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='visitime',
        ),
        migrations.AddField(
            model_name='visit',
            name='visittime',
            field=models.DateTimeField(db_column='visitime', null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='money',
            field=models.DecimalField(blank=True, db_column='money', decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='place',
            field=models.CharField(db_column='place', default='', max_length=256),
        ),
    ]
