# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-15 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestPlaces', '0003_auto_20170615_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visittime',
            field=models.DateTimeField(db_column='visittime', null=True),
        ),
    ]
