# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-15 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestPlaces', '0004_auto_20170615_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='duration',
            field=models.IntegerField(db_column='duration', null=True),
        ),
    ]
